name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Check format
        run: crystal tool format --check

  test:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
      - name: Install hunspell
        run: brew install hunspell
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Run tests
        run: crystal spec
