name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Check format
        run: crystal tool format --check

  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Install hunspell
        run: sudo apt-get install hunspell libhunspell-dev build-essential gettext
      - name: Build Hunspell from sources
        run: |
          wget https://github.com/hunspell/hunspell/releases/download/v1.7.2/hunspell-1.7.2.tar.gz
          tar xzvf hunspell-1.7.2.tar.gz
          cd hunspell-1.7.2
          autoreconf -vfi
          ./configure
          make
          sudo make install
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Run tests
        run: crystal spec
